### ISSUE TITLE
Can you release the zip file of the converted onnx file?

### ISSUE THREAD

**Issue by Baiyuetribe** [agizmo/onnx-stablediffusion-scripts#1]
```
from diffusers import StableDiffusionOnnxPipeline
pipe = StableDiffusionOnnxPipeline.from_pretrained("./stable_diffusion_onnx", provider="DmlExecutionProvider")
prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0] 
image.save("astronaut_rides_horse.png")
```
I want to get this folder directly`"./stable_diffusion_onnx"`，because I can't get the results on my side

**Comment by agizmo** [comment]
I don't feel comfortable providing the stable diffusion weights. Plus the total file size is 5GB+.

You should be free to try following harishanand95's instructions for downloading and converting the weights yourself. See the **Convert Stable Diffusion model to ONNX format** section at [https://huggingface.co/CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4) You will need to sign up for a free account at [HuggingFace.co](https://huggingface.co), accept the agreement for the Stable Diffusion repo at [https://huggingface.co/CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4), and obtain an account access token at [https://huggingface.co/settings/tokens](https://huggingface.co/settings/tokens)
